### ISSUE TITLE
Error: Network Error

### ISSUE THREAD

**Issue by markhomoki** [axios/axios#1608]
#### Summary

I have a weird issue, which I tried to debug without luck. I launched my app couple days ago in App Store and everything worked fine and even now for most users is working fine. My app is written in React Native and the API Server is using SSL, Xcode setup properly to handle and whitelist the API URL.

2 days ago I received a feedback that 3 GET calls don't load properly. 

My app has 4 tabs on the bottom and doing the following 4 requests on startup:

1. GET /events?page=1&four_five_extra_query_params
2. GET /users/me <- without any params
3. GET /messages?page=1
4. GET /notifications?page=1

To make these calls, first I am authenticating the user via a POST requests which **works fine in every case.**

The issue is, for some users when they launch the app the 1st, 3rd and the 4th tab is just loading without any results (**the 2nd tab always load properly**). Yesterday for 10 minutes my 1st phone had the same issue so quickly tried to debug it. To make it clear, **the API server is not down**, during these unsuccessful loads from the app, I can make requests to those endpoints from other phones and Postman. Since then my app is working again properly **without a single line of change.**

This was the error from Google Chrome Debugger:
![image](https://user-images.githubusercontent.com/8550329/41498120-4ef7abf0-715d-11e8-8009-fdbded17b7dd.png)

Today my 2nd phone started to have this issue, while it's working perfectly on my 1st phone. So I am still debugging it to come up with a solution. The weird part is if I change the endpoint on the 2nd phone to just **/events** it loads instantly if I change back to **/events?page=1&four_five_extra_query_params** then it doesn't and also doesn't send the request to the server. If I change the query args or even if just add one to it the app sends the request to the API and loads correctly.

Also a funny thing, I moved my API server to another subdomain, connected to that URL in debugging and everything worked fine, then changed back to the old subdomain and doesn't work.

The only thing I can think of which doesn't really make sense that the axios or one of the networking lib caches the endpoint and that's why doesn't send the request to the server. **In those cases when I checking the API server's log those requests don't reach the API server.**

I know it's a weird issue, I've never seen this before but I hope someone can help and that'd be great. :)

#### Context

- axios version: v0.18.0
- Environment: react-native: 0.55.4, iOS: 11.4

**Comment by markhomoki** [comment]
If anyone interested how I fixed it, here it is:

As I thought at the beginning it was a cache issue when I disabled the cache through the headers it didn't work:
```
axios.defaults.headers = {
	provider: headers.provider || null,
	token: headers.token || null,
	'Content-Type': 'application/x-www-form-urlencoded',
	'Cache-Control': 'no-cache, no-store, must-revalidate',
	'Pragma': 'no-cache',
	'Expires': 0,
	'Accept': 'application/json',
};

```

So now I commented out 'Cache-Control', 'Pragma', 'Expires', 'Accept' header tags and added an extra query arg with the current timestamp to all the GET calls, like this:
```
get(url) {
	// workaround to fix the caching issue on GET requests
	const currentTimePrefix = url.indexOf('?') === -1 ? `?` : '&';
	const currentTimeArg = `${currentTimePrefix}time=${new Date().getTime()}`;
	const fixedUrl = `${url}${currentTimeArg}`;

	return this.send(fixedUrl, 'GET');
}
```

This solution is working now, I don't think this is the best solution I could have come up but it is definitely working. If anyone has a better solution please share it.

**Comment by dengue8830** [comment]
im having a similar issue. Some request fails randomly, i wrote an error handler trying to collect any useful clue. Im getting this

error: Network Error
my collected data: {"status":0,"method":"post","response":"closed"}

now im rewriting the error handler to collect more data but this error doesn't follow any pattern, its totally random. 

I could reproduce the error when i had very bad mobile internet connection, but sometimes it occurs with WiFi, and it fails the original request but not the next request for report the error ... so weird

**Comment by jasonandres** [comment]
@dengue8830 We are experiencing the same issue. Front end react App(s) with backend NodeJS Express API.  We have 500k requests per week and receive one or two of these network errors from Axios per day, but the next request for reporting the error is successful.  Our API is up and not under any heavy load and the request never makes it to our API.

Did you find anything after collecting more data?

**Comment by dengue8830** [comment]
@jasonandres no, i can't see the cause of the weird behavior. I only see that is more common on android 5 (even more common with mobile network). This is my react native project package.json

```
{
  "name": "xxx",
  "version": "0.0.1",
  "private": true,
  "proxy": "http://localhost:8080",
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start --config ../../../../rn-cli.config.js",
    "test": "jest",
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "server": "react-native start"
  },
  "dependencies": {
    "axios": "0.18.0",
    "geolib": "2.0.24",
    "human-readable-ids": "1.0.4",
    "react": "16.3.1",
    "react-native": "0.55.4",
    "react-native-device-info": "0.21.5",
    "react-native-exit-app": "1.0.0",
    "react-native-fbsdk": "0.7.0",
    "react-native-fetch-blob": "0.10.8",
    "react-native-firebase": "4.2.0",
    "react-native-geocoding": "0.3.0",
    "react-native-gifted-chat": "0.4.3",
    "react-native-image-picker": "0.26.10",
    "react-native-linear-gradient": "2.3.0",
    "react-native-maps": "0.19.0",
    "react-native-masked-text": "1.7.1",
    "react-native-mauron85-background-geolocation": "0.5.0-alpha.34",
    "react-native-parallax-scroll-view": "0.21.0",
    "react-native-picker-select": "3.1.1",
    "react-native-signature-capture": "0.4.9",
    "react-native-snap-carousel": "3.7.0",
    "react-native-star-rating": "1.0.9",
    "react-native-step-indicator": "0.0.7",
    "react-native-swipe-list-view": "1.0.3",
    "react-navigation": "2.0.4",
    "react-redux": "5.0.7",
    "redux": "4.0.0",
    "redux-devtools-extension": "2.13.2",
    "redux-thunk": "2.3.0",
    "underscore": "1.9.0",
    "validator": "10.3.0"
  },
  "devDependencies": {
    "@types/axios": "0.14.0",
    "@types/geolib": "2.0.23",
    "@types/jest": "22.2.3",
    "@types/node": "9.6.8",
    "@types/react": "16.3.14",
    "@types/react-native": "0.55.14",
    "@types/react-navigation": "1.5.11",
    "@types/react-redux": "6.0.2",
    "@types/react-test-renderer": "16.0.1",
    "@types/redux": "3.6.0",
    "@types/underscore": "1.8.8",
    "@types/validator": "9.4.1",
    "babel-jest": "22.4.4",
    "babel-preset-react-native": "4.0.0",
    "jest": "22.4.4",
    "react-native-typescript-transformer": "1.2.5",
    "react-test-renderer": "16.3.1",
    "ts-jest": "22.4.6",
    "typescript": "2.8.3"
  },
  "jest": {
    "preset": "react-native",
    "transform": {
      ".+\\.tsx?$": "ts-jest"
    },
    "testRegex": "(/__tests__/.*|(\\.|/)(test|spec))\\.(jsx?|tsx?)$",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ],
    "modulePaths": [
      "<rootDir>"
    ]
  }
}
```

i saw others comments about react-navigation causing problems with another libs... may be this could be the case

i'm using node + express too, but the failed request doesn't hit the api (a saw logs)

have you get some clue?

**Comment by gabrielpiassetta** [comment]
We are having the same issue here. Axios v0.18, Flask Backend. Some of our customers are experiencing network erros randomly. One of them can reproduce the error all the time, but only in one machine, brand new one, anonymous tab. Add ?time in the query string didn't solve the issue.

**Comment by dengue8830** [comment]
in react native: i solved with this
```
- upgrade to rn57
- upgrade to nginx 1.15.3
- use https. I don't know if this help but i used anyway
```
so the problem was incompatible request config between okhttp and nginx

in web: i didn't see this error

**Comment by noqcks** [comment]
@gabrielpiassetta Did you ever solve this issue? We're experiencing it as well, but are unable to reproduce. It seems to be only coming from mobile devices.  

What versions are you running?

axios: 0.18.0
flask: 0.12.4
flask-CORS: 3.0.6 
nginx: 1.15.8

**Comment by gabrielpiassetta** [comment]
@noqcks Turns out that the problem was with our apache configuration, specifically in mpm_event.conf.

KeepAlive was off, setting it to on solved the issue.

**Comment by shuangyu** [comment]
suffering from this same issue couple of days!!! Everything works fine on iOS, while on Android phone,  sometimes it works fines, sometimes i always get network error!!

**Comment by say95** [comment]
> suffering from this same issue a couple of days!!! Everything works fine on iOS, while on Android phone, sometimes it works fines, sometimes i always get network error!!

@shuangyu Did u find any solution for this problem?

**Comment by Josin22** [comment]
> If anyone interested how I fixed it, here it is:
> 
> As I thought at the beginning it was a cache issue when I disabled the cache through the headers it didn't work:
> 
> ```
> axios.defaults.headers = {
> 	provider: headers.provider || null,
> 	token: headers.token || null,
> 	'Content-Type': 'application/x-www-form-urlencoded',
> 	'Cache-Control': 'no-cache, no-store, must-revalidate',
> 	'Pragma': 'no-cache',
> 	'Expires': 0,
> 	'Accept': 'application/json',
> };
> ```
> 
> So now I commented out 'Cache-Control', 'Pragma', 'Expires', 'Accept' header tags and added an extra query arg with the current timestamp to all the GET calls, like this:
> 
> ```
> get(url) {
> 	// workaround to fix the caching issue on GET requests
> 	const currentTimePrefix = url.indexOf('?') === -1 ? `?` : '&';
> 	const currentTimeArg = `${currentTimePrefix}time=${new Date().getTime()}`;
> 	const fixedUrl = `${url}${currentTimeArg}`;
> 
> 	return this.send(fixedUrl, 'GET');
> }
> ```
> 
> This solution is working now, I don't think this is the best solution I could have come up but it is definitely working. If anyone has a better solution please share it.

still not working on android 9 when I upload file

**Comment by Josin22** [comment]
I found a solution that makes sure your file path is start with 'file://' on Android when you upload the file.
which means, {uri:'file://'+your file path,name:your file name,type: your file type}

**Comment by KBiswas98** [comment]
1. change from **localhost** to your **ip**
2. add **http://** 

http://192.168.43.49:3000/user/

**Comment by geremora** [comment]
I having the same error. Totally random "Network error".  Around 1 of 20 requests gives that error. 

The API works perfectly, I made some stress tests from postman (runner) of hundreds of requests without any error.

The network error appears in our ios mobile app using: 

 "react-native": "0.61.2",
 "axios": "^0.19.2",


```
export const HTTP = axios.create({
  timeout: 30 * 1000, // 30 sec
});
HTTP.interceptors.request.use(addHeaders);
HTTP.interceptors.response.use(undefined, parseResponseError);
```

```
function addHeaders(request) {
  if (isRequestToOurAPI(request.url)) {
    request.headers['Accept'] = 'application/json';
    request.headers['Content-Type'] = 'application/json; charset=utf-8'; 
    request.headers['X-Parse-Application-Id'] = PARSE_CONFIG.APPLICATION_ID;
    request.headers['X-Parse-REST-API-Key'] = PARSE_CONFIG.REST_API_KEY;
  }
  return request;
}
```

```
function parseResponseError(error) {
  let message = get(error, 'response.message');
  if (!message) {
    message = get(error, 'response.code') || get(error, 'response.data.error') || error.message;
  }
  if (message) {
    const status = get(error, 'response.data.code');
    if (status) {
      Alert.alert(`Status ${status}`, message);
    }
    else {
      Alert.alert(JSON.stringify(error));
    }
    return Promise.reject({
      status: status || 400,
      message,
    });
  }
  else {
    Alert.alert(JSON.stringify(error));
  }
  return Promise.reject(error);
}
```
