### ISSUE TITLE
Setting 'Content-Type' header does not work.

### ISSUE THREAD

**Issue by star-collector** [axios/axios#2544]
It seems like setting `Content-Type` header is impossible without `data` property:

```js
const api = Axios.create({
  baseURL: 'https://my-url',
  headers: {
    'Accept': 'application/json',
    'Content-Type': 'application/json',
  },
});

api.post('/post-something'); // The request doesn't contain 'Content-Type' header.
api.get('/get-something', {
  headers: { 'Content-Type': 'application/json' }
}); // Still no 'Content-Type' header.

api.post('/post-something', null); // Works. 'Content-Type' is present in the request.
api.get('/get-something', {
  data: {},
  headers: { 'Content-Type': 'application/json' }
}); // Works as well.
```

**Comment by Alanscut** [comment]
indeed, in browser environment, the `Content-Type` will be removed if data is undefined. Because there is no need to set the `Content-Type` when no data to transfer.

https://github.com/axios/axios/blob/841466416b6851666955113a60ae46830a27003f/lib/adapters/xhr.js#L119-L129

**Comment by star-collector** [comment]
>Because there is no need to set the Content-Type when no data to transfer.

True, but some backend systems still require it to be passed specifically, even if there are no data to transfer. Backend I have to work with returns an error when there is no `Content-Type` present.

Also, it seems like the same bug was already fixed once. #86

**Comment by Alanscut** [comment]
That fix(https://github.com/axios/axios/commit/3c4dfe8a8112d685e0cdaf8d96c18e0258b8b129) actually was about case of `content-type`  https://github.com/axios/axios/issues/86#issuecomment-124166997 , mzabriskie mistakenly thought that #86  is the same kind of problem, so this issue still exists.
As you said, setting Content-Type header is impossible without data property currently.

@yasuf , should axios surpport this feature?
