### ISSUE TITLE
responseType=text but json is parsed

### ISSUE THREAD

**Issue by neg3ntropy** [axios/axios#2791]
**Describe the bug**

I want to get a response as string even if that comes as application/json. Parsing the response to an object is not required and not desired as the only thing I have to do with it is rewrite some urls and I am not sure of the content type the server will use.

**To Reproduce**

Server:
```js
const http = require("http");
const server = http.createServer((req, res) => {
    res.writeHead(200, {"Content-Type": "application/json"});
    res.end("{\"doNotParse\": 1}");
});
server.listen(1234);
```
Client:
```js
const axios = require("axios");   
axios.request({url: "http://localhost:1234/", responseType: "text"})
     .then(res => console.log("Type of data is %s", typeof res.data));
```
Outcome:
>  Type of data is object

**Expected behavior**
response `data` should be the string `"{\"doNotParse\": 1}"`, the program would print:

>  Type of data is string

**Environment:**
 - Axios 0.19.2
 - Fedora 31
 - Node 12

**Additional context/Screenshots**
Setting `transformResponse: (data) => data` appears to do the trick, regardless of `responseType`.

**Comment by determin1st** [comment]
What you think should be the default content type returned in the case of this option enabled:

- ArrayBuffer
- String

**Comment by neg3ntropy** [comment]
I am not familiar with browsers, but it looks like responseType=text should result in strings. For ArrayBuffer there's responseType=arraybuffer.

**Comment by determin1st** [comment]
did you try using axios `config`?

**Comment by neg3ntropy** [comment]
you can see that from the code posted "to reproduce".

**Comment by determin1st** [comment]
oke, tested..

```javascript
    axios({
      url: "http://localhost:1234/",
      //responseType: "text",
      transformResponse: []
    }).then(function(res) {
      console.log("Type of data is %s", typeof res.data);
    });
```
that happens because of `transformResponse` has one function which transforms from JSON, so you may make it empty to opt-out of this behaviour

**Comment by sagar-gavhane** [comment]
What do you think about this?

```javascript
const instance = axios.create({
  baseURL: 'https://jsonplaceholder.typicode.com/',
  transformResponse: (data) => JSON.stringify(data)
});

const fetchUserInStringType = async () => {
  const response = await instance.get('/users/1')  
  console.log(response.data)
}

fetchUserInStringType()
```

**Comment by determin1st** [comment]
the main thought here, is why one option is choosen against another. should they depend on each other and stuff..

**Comment by liesauer** [comment]
+1
```
const response = await axios.get(url, {
    responseType: 'text',
    transformResponse: [data => data],
});
// get html string or others string
console.log(response.data);
```
works for me, but honestly, this is really bad...setting `responseType` to `text` suppose to return string but do nothing actually and keep trying to parse as json with no reason...

**Comment by jasonsaayman** [comment]
Fixed with #3688

**Comment by KaKi87** [comment]
Hello,
@jasonsaayman Are you talking about OP's issue ?
Because I'm still experiencing it in v0.27.2 and forced to use @liesauer's workaround.
Thanks

**Comment by joe733** [comment]
Hi, is this behaviour expected?

```ts
// standard
import fs from "fs";
import path from "path";

// external
import axios, { AxiosError } from "axios";

async function request() {
  const url = "https://api.github.com";
  const localFileName = path.join(__dirname, "response.txt");

  try {
    const response = await axios.get(url, {
      responseType: "text",
      transformResponse: [(data) => data],
    });
    fs.writeFile(localFileName, response.data, (fsError) => {
      if (fsError) {
        throw fsError;
      }
    });
  } catch (error) {
    if (error instanceof AxiosError) {
      console.error(error.response.status, error.response.statusText);
    } else {
      console.error(error);
    }
    return null;
  }
}

request();
```

JSON data gets written to a text file. I want to accept only files like at https://www.gnu.org/licenses/gpl-3.0.txt

**Comment by monika-pant** [comment]
still the same issue i am experienceing with "axios": "=1.3.3"
