### ISSUE TITLE
Axios doesn't address memory leaks?

### ISSUE THREAD

**Issue by yizhengfeng-jj** [axios/axios#3217]
#### Describe the bug
I used the latest version of Axios (v0.20.0-0) with interceptors, interceptors.response.use () after that, the sent request will be viewed through the chrome tool. The returned content will always be saved and will not be released. This problem should be very common and should have been solved earlier. Is there a problem with my configuration? I hope you can get a reply. Thank you very much

#### To Reproduce
Pseudo code

```js
servers.interceptors.response.use();
```

#### Expected behavior

I send requests to intercept, but don't leak memory
#### Environment
 - Axios Version 0.20.0-0
 - Browser Chrome
 - Browser Version 84.0.4147.125
 - Node.js Version 14.0.1
 - Additional Library Versions React 16.7

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by dexturr** [comment]
We also encountered this issue when we bumped from 0.19.2 -> 0.20.0. Reverting managed to fixed the issue.

**Comment by yizhengfeng-jj** [comment]
> We also encountered this issue when we bumped from 0.19.2 -> 0.20.0. Reverting managed to fixed the issue.

Thank you very much for your reply. Do you mean that 0.19.2 version of Axios does not have the above class leakage problem. I see this problem in 0.18.1 and v.20.0

**Comment by dexturr** [comment]
We were using 0.19.2 with no issues. We bumped to 0.20.0 and an issue arose with a box running out of memory and crashing. We used interceptors and found the response was not being released, as you described. Slowly leaking and eventually dying. We reverted back to 0.19.2 and everything seems to have gone back to ok. I cannot speak for 0.18.1 myself as this was for a prototype and we never used 0.18.1 on it so there may have been bug fixes in between 0.19.2 and 0.18.1.

Otherwise if you're still having issues on 0.19.2 we may have had different root issues. I have never really used axios, so you're probably way ahead of me if it's a config thing. I was just the unlucky person assigned to finding the issue 👍

**Comment by haliloncen** [comment]
if you are using to the axios without create instance,
you can try below code;

```javascript
const axios = axios.create({...}) // instead of axios.get(), post(), put() etc.
```
It works with 0.20.0 without memory leaks.

**Comment by Ks89** [comment]
Same issue, I downgraded to 0.19.2 as suggested and it seems to be ok.

**Comment by KyruCabading** [comment]
Do we still have this memory leak issue?

**Comment by Rachnerd** [comment]
I can confirm the memory leak is still present in "axios": "^0.21.0".

**Comment by dan-j** [comment]
I've just ran into the same problem but assumed it was my code. Then after some refactoring and the bug still occurring, I searched and came across this issue.

Using 0.19.2, I haven't tried down/upgrading yet.

**Comment by water-a** [comment]
I'm on version 0.21.1 and encountering this issue. The data from the responses isn't being garbage collected.

**Comment by joquijada** [comment]
> I'm on version 0.21.1 and encountering this issue. The data from the responses isn't being garbage collected.

I experienced the same with version 0.21.1, here's my comment on another issue with I think relates more to this issue, https://github.com/axios/axios/issues/2143#issuecomment-798813342. On 0.19.x we had no issues. On 0.21 the memory and file descriptor leak started. I followed verbatim [the workaround found in this other comment of that issue](https://github.com/axios/axios/issues/2143#issuecomment-495994940) and it worked for me

**Comment by jasonsaayman** [comment]
This is an issue that needs to be fixed irrespective of SemVer, I am tagging it and will try get to work on it as soon as possible. If anyone wants to give it a shot please try and open a pull request and add me as a reviewer or assign me.

**Comment by joquijada** [comment]
I'll try to take a look at the issue outside of my work hours and submit a PR if no one has beat me to it, by this Sunday unless it turns out to be a bigger type fix. I haven't contributed to this project before so there's also a bit of ramp up for me. Cheers!

**Comment by jasonsaayman** [comment]
@joquijada Thanks, please just tag me in it so that I can have a look and get it merged asap

**Comment by joquijada** [comment]
> @joquijada Thanks, please just tag me in it so that I can have a look and get it merged asap

I've done some investigation and have narrowed down the problem some. In my case the FD/memory leak happens when `options.maxRedirects > 0`, in which case [lib/adapters/http.js](https://github.com/joquijada/axios/blob/master/lib/adapters/http.js) is using the [follow-redirects](https://github.com/follow-redirects/follow-redirects/blob/main/index.js) library. Unfortunately in case of redirects, the `request.setTimeout()` function gets called on the original request only, and not on the redirect requests. This means the sockets hang around forever unless explicitly destroyed, as indicated in the [NodeJS documentation](https://nodejs.org/api/net.html#net_socket_settimeout_timeout_callback),

![image](https://user-images.githubusercontent.com/25803738/112084642-8ab1e380-8b5f-11eb-922c-65df08dfce7a.png)

When I change the request URL so that a redirect does not happen, hence the native NodeJS http/https libraries are used, no leak whatsoever since there's only a single request involved.

This is what I think the problem in. Tomorrow I'll write a wrapper around the follow-redirects library to manually set a timeout in all the redirect requests, and see if that solves the issue with memory leaks when there are redirects involved.

**Comment by jasonsaayman** [comment]
@joquijada Thanks that sounds great. Very in depth look into this. Please remember to tag me in the pull request then I can get that out ASAP

**Comment by DigitalBrainJS** [comment]
Probably, this has been fixed in the follow-redirects v1.13.3 . They just had some potential leaks with event handlers in the overloaded `abort` [method](https://github.com/follow-redirects/follow-redirects/blob/5abfe3355dc3eafd8a1aa579387ea90598152532/index.js#L64-L73).

**Comment by joquijada** [comment]
> @jasonsaayman Probably, this has been fixed in the follow-redirects v1.13.3 . They just had some potential leaks with event handlers in the overloaded `abort` [method](https://github.com/follow-redirects/follow-redirects/blob/5abfe3355dc3eafd8a1aa579387ea90598152532/index.js#L64-L73).

Thanks for letting me know because I slept on it and realized it'd be infinitely easier for the fix to come from `follow-redirects`. I'll check out v1.13.3 of that library.

**Comment by jasonsaayman** [comment]
Ok cool thanks I will see if I can bump it without any repercussions.

**Comment by joquijada** [comment]
I know this issue was closed, but problem persists in follow-redirects v1.13.3. I've submitted [this PR ](https://github.com/follow-redirects/follow-redirects/pull/157)to that product.

**Comment by jasonsaayman** [comment]
Ok cool please reference this and I will reopen

**Comment by joquijada** [comment]
> Ok cool please reference this and I will reopen

Done. I've added steps to reproduce in [that issue](https://github.com/follow-redirects/follow-redirects/issues/156).

**Comment by joquijada** [comment]
Update: The `follow-redirects` team has merged in [the socket leak fix](https://github.com/follow-redirects/follow-redirects/pull/157)  and created [a new release](https://github.com/follow-redirects/follow-redirects/commit/bbe5769c556f797070c5281efeed3bd2b3f8110b).

**Comment by jasonsaayman** [comment]
Thanks I will update Axios
