### ISSUE TITLE
Type of return from Axios request in TypeScript seems incorrectly unwrapped

### ISSUE THREAD

**Issue by RenegadeMaster** [axios/axios#3363]
#### Describe the bug
When using Axios with Typescript, Typescript compiler seems to incorrectly presume data is unwrapped from AxiosResponse object.

#### To Reproduce
Example 

I have several API's which use Axios as follows:

```ts
export class CaseApi extends HttpClient {

    public getCases():  Promise<AxiosResponse<Case[]>> {
        return this.instance.get<Case[]>('/stack');
    }
}
```

httpclient.ts:

```ts
import axios, { AxiosInstance, AxiosResponse } from 'axios';

declare module 'axios' {
    interface AxiosResponse<T = any> extends Promise<T> {}
}

export abstract class HttpClient {
    protected readonly instance: AxiosInstance;

    public constructor(baseURL: string) {
        this.instance = axios.create({
            baseURL,
        });


    }
}
```

Using this method as follows:

```ts
fetchFreshCaseStack(){
        let results = await CaseApi.getInstance().getCases();
        console.log(results);
        // this.setStack(results);
};
```

#### Expected behavior
I would expect "results" in above sample to have type AxiosResponse<Case[]>
If I log response to console this is indeed true.
However typescript interprets type of results as simple Case[]
This prevents me from using await/async methodology. Everythign works as expected uses promises though.

#### Environment
 - Axios Version  0.20.0
 - Adapter N/A
 - Browser N/A (issue flagged by compiler)

 - Node.js Version 10.21.0
 - OS: Ubuntu 18.04
 - Additional Library Versions Vue 3.1.2

#### Additional context/Screenshots
Typescript infers return as Case[]
![type1](https://user-images.githubusercontent.com/963569/97010472-bd6e9600-1545-11eb-8383-437b4fa19935.png)

Logging data shows type is actually AxiosResponse and data is Case[]
![type2](https://user-images.githubusercontent.com/963569/97010565-db3bfb00-1545-11eb-89a6-d0c3f690eeca.png)

**Comment by codewitch** [comment]
I am experiencing the same issue.

**Comment by ariabuckles** [comment]
I may have figured out where this is coming from: we had the following override of the type for `AxiosResponse`

```typescript
declare module 'axios' {
  export interface AxiosResponse<T = any> extends Promise<T> {}
}
```

From a pattern people have been using for interceptors:

https://github.com/axios/axios/issues/1510#issuecomment-448201698

Since that issue has been solved, hopefully we can all migrate away from this override. At least in our codebase removing that didn't cause any new errors.

**Comment by jasonsaayman** [comment]
Hi 👋 

Please could you retry with the latest version and open a new issue should this error still be relevant?

Thanks
