### ISSUE TITLE
POST FormData still creates Network Error on Android with 0.27.2

### ISSUE THREAD

**Issue by zaubara** [axios/axios#4800]
#### Describe the bug
On Android in Expo 45 / React Native 0.68 with Hermes (and Flipper), POSTing a FormData object fails instantly with a Network Error. Works on iOS. Axios 24 works and seems to be the last reliable version.
 

#### To Reproduce

```js
const fd = new FormData()
fd.append('some_text', text1)
fd.append('more_text', text2)
fd.append('only_text', text3)
try {
    const response = await api.post('endpoint', fd)
    return response
} catch (e) {
    console.log(e)
    return
}
```

#### Expected behavior
No network error.

#### Environment
 - Axios Version: 0.27.2
 - OS: Android 11
 - Additional Library Versions: Expo 45, React Native 0.68

**Comment by DigitalBrainJS** [comment]
Solving the issue that can occur in the ReactNative environment is difficult, as it seems that none of the contributors use RN in their daily work in order to be able to quickly create a test environment to fix the bug. At the same time, reports on the workability of FormData in ReactNative are quite inconsistent.

Could you please run this test code on the affected platform and post the log here?

```js
import axios from "axios";
import utils from "axios/lib/utils.js";

const form = new FormData();
const prototype = FormData.prototype;

console.log(
  JSON.stringify({
    VERSION: axios.VERSION,
    client: typeof navigator !== "undefined" && navigator.userAgent,
    node: typeof process !== "undefined" && process.version,
    isFormData: utils.isFormData(form),
    toString: String(form),
    stringTag: form[Symbol.toStringTag],
    constructor: prototype.constructor,
    props: Object.getOwnPropertyNames(prototype)
  })
);
```

**Comment by zaubara** [comment]
Sure:
{"VERSION":"0.27.2","isFormData":true,"toString":"[object Object]","props":["constructor","append","getParts"]}

**Comment by zaubara** [comment]
I think it's more readable without the stringify:
<img width="238" alt="Bildschirmfoto 2022-06-20 um 16 14 34" src="https://user-images.githubusercontent.com/6575317/174621318-3e550d34-fee7-49ea-807f-9feba2efa524.png">

**Comment by mantusuff420** [comment]
Same issue for me too

**Comment by DigitalBrainJS** [comment]
@zaubara thanks! It seems we need an additional test since it's not a typical problem with FormData instance detection.
One more test:
```js
  function isStandardBrowserEnv() {
    let product;
    if (typeof navigator !== 'undefined' && (
      (product = navigator.product) === 'ReactNative' ||
      product === 'NativeScript' ||
      product === 'NS')
    ) {
      return false;
    }

    return typeof window !== 'undefined' && typeof document !== 'undefined';
  }

  function isFormData(thing) {
    const pattern = '[object FormData]';
    return thing && (
      (typeof FormData === 'function' && thing instanceof FormData) ||
      toString.call(thing) === pattern ||
      (typeof thing.toString === 'function' && thing.toString() === pattern)
    );
  }

  console.log('product', typeof navigator !== 'undefined' && navigator.product);
  console.log('Platform', typeof Platform !== 'undefined' && Platform);
  console.log('axios:isStandardBrowserEnv', isStandardBrowserEnv());
  console.log('axios:isFormData', isFormData(new FormData()));

  ((name) => {
    try {
      const xhr = new XMLHttpRequest();
      xhr.open('POST', 'https://httpbin.org/post');
      const formdata = new FormData();
      const text = 'This is awesome';
      formdata.append('title', text);
      xhr.onerror = console.warn;
      xhr.onloadend = () => {
        console.log(`[${name}] ${JSON.parse(xhr.response).form.title}`);
      }
      xhr.send(formdata);
    } catch (err) {
      console.warn(err);
    }
  })('without content type');

  ((name) => {
    try {
      const xhr = new XMLHttpRequest();
      xhr.open('POST', 'https://httpbin.org/post');
      const formdata = new FormData();
      const text = 'This is awesome';
      formdata.append('title', text);

      xhr.setRequestHeader('Content-Type', 'multipart/form-data');

      xhr.onerror = console.warn;
      xhr.onloadend = () => {
        console.log(`[${name}] ${JSON.parse(xhr.response).form.title}`);
      }
      xhr.send(formdata);
    } catch (err) {
      console.warn(err);
    }
  })('with content type')
```

**Comment by zaubara** [comment]
Different device, but still getting the same error, so it should be identical:

```
product ReactNative
Platform false
axios:isStandardBrowserEnv false
axios:isFormData true
[with content type] This is awesome
[without content type] This is awesome
```

**Comment by tanengsiang** [comment]
I also facing this issue for the network error, below  is the screen shot.
![error_resubmit](https://user-images.githubusercontent.com/108261452/175888600-8ba9d22f-eb8a-4fab-a9ce-481a0d6d026e.png)

work fine in iOS simulator but in my android
device will pop out above error .

below is my api code : 

resubmitLeave = ()=>{ // This api is post the resubmit leave record
       
        LoadingModal.show();
        const form = new FormData();

        Object.keys(this.state).forEach((key)=>{
            if (key == 'Hours'){
                form.append(key, parseFloat(this.state[key]));
            }else if (key == 'Days'){
                form.append(key, this.state.LeaveKind == 'Hourly' ? 0 : parseFloat(this.state[key])); 
            }else{

                form.append(key, this.state[key]);
            }
        })
        
        api.post('api/ResubmitLeaveForm', form).then((res) => {
            
            console.log(res, '----------------------  from resubmit leave respond')
            
            AlertBox.showModal('success', '', 'Resubmit Leave Form Success!');
            LoadingModal.close();
           this.props.onFinish();
       
        }).catch((err) => {
            console.error(err, '----------------------  from resubmit leave respond err');
            AlertBox.showModal('error', '', err[0].Message[0]);
            this.props.onFinish();
            if (err && !(err instanceof Error)) {
                let temp = [];
                let error = [];
                error = err[0]['Message'];
                error.forEach((each) => {
                    temp.push(each);
                })
                this.setState({
                    message: {
                        status: true,
                        error: temp
                    }
                })
            } else {
                //System error or runtime error
            }
            LoadingModal.close();
        
        })
  

axios version : "^0.19.0",
expo version : 41,
OS : Android 10 , 
React Native Version : 0.69.0

**Comment by Slapbox** [comment]
@zaubara do you see any network request in the debugger's Network tab from Axios?

We seem to be having this same issue, and we do not see Axios creating any network request in the Network tab.

**Comment by mlazari** [comment]
The issue is that axios is setting a wrong `Content-Type` header if you don't pass it explicitly. See https://github.com/axios/axios/issues/4823#issuecomment-1224615032

**Comment by Slapbox** [comment]
@mlazari we explicitly set the `'Content-Type': 'application/x-www-form-urlencoded'` but we still have the issue.

**Comment by mlazari** [comment]
@Slapbox That doesn't change anything since you set the same value as the default. I think you must use `'Content-Type': 'multipart/form-data'` when you use FormData. From my debugging if you send FormData with the default `'Content-Type': 'application/x-www-form-urlencoded'` it doesn't make the request at all on Android and `XMLHttpRequest.onerror` is called here: https://github.com/axios/axios/blob/v0.27.2/lib/adapters/xhr.js#L116 which causes the rejection with "Network Error".

Note that if you use `FormData` from [form-data](https://www.npmjs.com/package/form-data) you'll likely need this workaround: https://github.com/axios/axios/issues/4412#issuecomment-1025506556. But recently I found that there is a global `FormData` available in React Native that you can use and that works without that workaround.

**Comment by jjspierx** [comment]
I was having the same issue.  Spent and entire day on it.  Rolled back to Axios 0.24.0 and it started working.

**Comment by CaioMars** [comment]
**React Native**

Hey guys, I spent hours on this and the only way I could get it to work was to downgrade to 0.24.0 as @jjspierx mentioned.

      const formData = new global.FormData()
      formData.append('file', data)

      const response: PostImageResponse = await http({
        method: 'POST',
        url: `/document/link/${docId}`,
        headers: {
          'Content-Type': 'multipart/form-data',
        },
        data: formData,
      })

Where http is a utility that sets up and calls axios along with the config object parameter shown above.

**Version:**
React: 18.0.0
Expo: ~46.0.9
Axios: 0.24.0

**Comment by Rhadammanthis** [comment]
This is still happening with
`react-native: 0.64.0`
but I'm glad(?) to add that downgrading axios worked for us too

**Comment by Josef-Marie** [comment]
same issue too 
this is what am getting 

FormData {
  "_parts": Array [
    Array [
      "Image",
      Object {
        "name": "my_image.jpg",
        "type": "image/jpg",
        "uri": undefined,
      },
    ],
    Array [
      "user",
      "18",
    ],
    Array [
      "Message",
      "Good to go ",
    ],
    Array [
      "symptoms",
      "Abortion",
    ],
    Array [
      "cattleType",
      "Inka zikamwa",
    ],
    Array [
      "Sector",
      "Rwimiyaga",
    ],
  ],
}
[AxiosError: Network Error]

**Comment by CaioMars** [comment]
It got it to work with `"axios": "0.24.0"` only.

**Comment by paruckerr** [comment]
```
react: 17.0.1 => 17.0.1
react-native: 0.64.3 => 0.64.3
```

Still not working with `"axios": "^0.24.0"`

**Comment by paruckerr** [comment]
I resolve the **network error** problem setting file like this

```
{
    name: 'files',
    type: 'image/png',
    uri: Platform.select({ ios: file.uri.replace('file://', ''), android: file.uri }),
}
```

info

```
react: 17.0.1
react-native: 0.64.3
react-native-image-crop-picker: ^0.38.1
```

**Comment by Roucoz** [comment]
only downgrading to version 0.24.0 works.

**Comment by paruckerr** [comment]
> only downgrading to version 0.24.0 works.

I had already downgraded, but the way I was passing the object caused the error too, so I added the info above if helps.

**Comment by Slapbox** [comment]
Does this still affect versions `1.0.0` and above? Can anyone report their findings?

**Comment by pnxdxt** [comment]
Fixed by add correct content type using the rpm mime pkg.

```js
import mime from "mime";

const newImageUri =  "file:///" + imageUri.split("file:/").join("");

const formData = new FormData();
formData.append('image', {
 uri : newImageUri,
 type: mime.getType(newImageUri),
 name: newImageUri.split("/").pop()
});
```

**Comment by mateusfg7** [comment]
> I resolve the **network error** problem setting file like this
> 
> ```
> {
>     name: 'files',
>     type: 'image/png',
>     uri: Platform.select({ ios: file.uri.replace('file://', ''), android: file.uri }),
> }
> ```
> 
> info
> 
> ```
> react: 17.0.1
> react-native: 0.64.3
> react-native-image-crop-picker: ^0.38.1
> ```

This works for me too, thanks!

**Comment by mateusfg7** [comment]
> Does this still affect versions `1.0.0` and above? Can anyone report their findings?

@Slapbox I'm on the v1.2.2, and I was facing the same issue until I try the solution of @paruckerr, and works!

**Comment by PrimulaX** [comment]
I had a similar problem about a year ago and didn't remember how I resolved it.  And again I have this problem, last time what I remember, it was okHttp bug on android, does anyone have more info about this?

**Comment by hemaliVadher** [comment]
FormData still creates Network Error on Android with 0.27.2. I have [AxiosError: Network Error] while uploading a document via react-native-document-picker@8.1.2. Please give me suggestions on how to resolve this.

**Comment by OKT92** [comment]
Solved my problem after adding headers content-type "multipart/form-data" instead of "x-www-form-urlencoded".

Axios version: 1.3.4

**Comment by zaubara** [comment]
Yes, this no longer creates an error. But depending on the configuration, it might create an empty or otherwise invalid formdata-request. 0.24 seemed to be the ONLY fix on android for me so far.

**Comment by vladimirevstratov** [comment]
```
const decodedFileUri = decodeURIComponent(fileUri); 
// on Android is equal to
// file:///data/user/0/my.app/files/folder-id/filename.ext

const decodedFileName = decodeURIComponent(fileName);

const iosFileUri = decodedFileUri.replace('file:///', '/'); 

formData.append('objectId', objectId);
formData.append('file', {
-->  uri: Platform.OS === 'ios' ? iosFileUri : decodedFileUri,
  type: mimeType,
  name: decodedFileName,
});
```

**Comment by sergioisidoro** [comment]
Adding the mime type also worked for me. On iOS seems to not be needed.

**Comment by mohamed2m2018** [comment]
> Solved my problem after adding headers content-type "multipart/form-data" instead of "x-www-form-urlencoded".
> 
> Axios version: 1.3.4

This worked with me

**Comment by mbachega** [comment]
> I was having the same issue. Spent and entire day on it. Rolled back to Axios 0.24.0 and it started working.

This solved my problem too. thanks very much!

**Comment by iamahannan** [comment]
### React Native 0.72.4

Network Error on Android disappeared by giving the following header in Axios.

`headers: {"content-type": "multipart/form-data"}`

**Comment by iabdulhannan** [comment]
### react Native 0.72.4

Network Error on POST-ing FormData in Android disappeared by giving the following headers:

`headers: {"content-type": "multipart/form-data"}`

**Comment by alexkendall** [comment]
Same issue here 0.72.1

**Comment by vokecodes** [comment]
Rolled back to     `"axios": "^0.24.0"` and it worked

**Comment by Kornelg96** [comment]
not working any of solution ; (

**Comment by Josh2941** [comment]
I was getting the same error. Spent several days and a lot of time upgrading packages and trying all the solutions from issues and stackoverflow. Finally this was the mistake which I don't think is mentioned which even in the docs.

If we have a `FormData` object

```
formData.append("name", "abc")
formData.append("state", undefined)
formData.append("address", {
    addressLine1: "",
    addressLine2: ""
});

```
It will throw the same error since the `"state"` is `undefined` and `"address"` is an object. But `FormData` accepts only string or File or Blob. So this was causing the issue for me. Once I replaced `undefined` with `""` and `"address"` with `JSON.stringify(addressObj)` it started working.

Reference -> https://stackoverflow.com/a/72899049/5918233

**Comment by kararalzawaid** [comment]
for android you just need to set header 
  const headers = {
        headers: {
          'Content-Type': 'multipart/form-data',
        }
      };
      
      and added to your axios header call

**Comment by mironovpib101** [comment]
I getting this problem on Android from expo. 
My search fail finished, but i fixed it!
My code:
![image](https://github.com/axios/axios/assets/14177243/0d47bc85-5f18-4002-b431-0890f00aa112)
I use mime on 65 line - no have result, and content-type dont help me on 74 line.
You need change http to https!
If json request running http on local development,  "content-type": "multipart/form-data", required https!
Creating nginx virtual host and proxy to local api, this is working! good luck
PS. usesCleartextTraffic = false dont work :(

**Comment by vajid-khan** [comment]
I was able to fix the issue with below cooe|
```javascript
const data = {}; //or FormData
const headers = {}; //your default headers

axios({
  url: "",
  method: "post",
  data: data,
  headers: {
    ...headers,
    ...(data instanceof FormData
      ? {
        "Content-type": "multipart/form-data"
      }
      : {})
    }
  });
```

**Comment by trantus** [comment]
I have to send a request strongly without any `Content-Type `, so adding `"Content-type": "multipart/form-data" `isn't a solution for me

**Comment by Aszurar** [comment]
2024, and I still have this problem, it doesn't happen every time, only sometimes and on Android.

As I said, it doesn't happen all the time, only once in a while, I haven't found a pattern for it.

I know that the file is filled, I have a log showing it before and in the request in the flipper the formData appears filled.

But out of nowhere, sometimes this network error happens, and when it happens, if you try to submit again, it works normally.

react native: 0.71.1
axios: 1.6.7


```js
     console.log("file", file)
    const formData = new FormData();
    formData.append('file', file);

    return api.put<IBaseResponse<IOnboardingResponse>>(
      submitEvidenceRoute,
      formData,
      {
        headers: { 'Content-Type': 'multipart/form-data' },
      },
    );
```

**Comment by Stargazer777777** [comment]
> 2024, and I still have this problem, it doesn't happen every time, only sometimes and on Android.
> 
> As I said, it doesn't happen all the time, only once in a while, I haven't found a pattern for it.
> 
> I know that the file is filled, I have a log showing it before and in the request in the flipper the formData appears filled.
> 
> But out of nowhere, sometimes this network error happens, and when it happens, if you try to submit again, it works normally.
> 
> react native: 0.71.1 axios: 1.6.7
> 
> ```js
>      console.log("file", file)
>     const formData = new FormData();
>     formData.append('file', file);
> 
>     return api.put<IBaseResponse<IOnboardingResponse>>(
>       submitEvidenceRoute,
>       formData,
>       {
>         headers: { 'Content-Type': 'multipart/form-data' },
>       },
>     );
> ```
> 
> I tried using mimo and the solutions above, but nothing... the worst thing is that it only happens once in a while, so I always have to test a lot to see if it solves it or not...

You really save my day!

**Comment by Amatefinde** [comment]
oh, thanks a lot! 
i am in middle of 2024 and they still don't fix it 

> I was having the same issue. Spent and entire day on it. Rolled back to Axios 0.24.0 and it started working.

**Comment by ashickantony** [comment]
> 2024, and I still have this problem, it doesn't happen every time, only sometimes and on Android.
> 
> As I said, it doesn't happen all the time, only once in a while, I haven't found a pattern for it.
> 
> I know that the file is filled, I have a log showing it before and in the request in the flipper the formData appears filled.
> 
> But out of nowhere, sometimes this network error happens, and when it happens, if you try to submit again, it works normally.
> 
> react native: 0.71.1 axios: 1.6.7
> 
> ```js
>      console.log("file", file)
>     const formData = new FormData();
>     formData.append('file', file);
> 
>     return api.put<IBaseResponse<IOnboardingResponse>>(
>       submitEvidenceRoute,
>       formData,
>       {
>         headers: { 'Content-Type': 'multipart/form-data' },
>       },
>     );
> ```
> 
> I tried using mimo and the solutions above, but nothing... the worst thing is that it only happens once in a while, so I always have to test a lot to see if it solves it or not...

did you find any solution, same issue happening for me.

**Comment by boiboif** [comment]
same issue

**Comment by arashfallahi1989** [comment]
I faced exactly the same issue today and managed to address it by replacing the image type with 'image/jpeg'.

**Old Code:**
```javascript
const data = new FormData();
data.append('image', {
  name: image.name,
  type: 'image',
  uri: image.path,
});

const response = await axios.post('/', data, {
  headers: {'content-type': 'multipart/form-data'},
});
```

**New Code:**
```javascript
const data = new FormData();
data.append('image', {
  name: image.name,
  type: 'image/jpeg',
  uri: image.path,
});

const response = await axios.post('/', data, {
  headers: {'content-type': 'multipart/form-data'},
});
```

This solved the issue for me. Hope it helps!

**Comment by UdumiziSolomon** [comment]
Still experiencing this issue 
`axios: ^1.7.2`
`expo: ~49.0.5`
`react-native: 0.72.10`

This is the request body on Android
the uri = `file:///data/user/0/x/cache/Print/70e29490-6cc7-499e-9567-ab2f08eacfdb.pdf`
   ```
 const body = new FormData();
    body.append('title', item?.title);
    body.append('document', {
      uri: uri,
      name: item?.title,
      type: mime.getType(uri),
    });
```

this is the axios request

```
export const useSendDocument = () => {
  return useMutation(
    async (body: any) => {
      const { data } = await SERVER.post(
        `/xxx/send-document`,
        body,
        {
          headers: {
            'Content-Type': 'multipart/form-data',
          },
        },
      );
      return data;
    },
    {
      onError: (error: AxiosError) => {
        handleAxiosError(error);
      },
    },
  );
};
```
I keep getting `'Network Error'` on Android, works well for IOS and also `NB:` every 1 out of 50 request sent on Android works. Any help would be appreciated.

**Comment by boiboif** [comment]
Try update axios version to latest and use fetch as adaptor. It work for me. I have tried 100 times formData post requests in a row without "network error".

**Comment by Roucoz** [comment]
again .. nothing work until i returned to version 0.24.0..
i am developing another app and the same error appeared. 0.24 wokrs

**Comment by fleuverouge** [comment]
Hi @UdumiziSolomon I got the same problem. Have you found any resolution?

**Comment by UdumiziSolomon** [comment]
I had to switch to fetch API

**Comment by yazantenjaz** [comment]
i don't know if this will work for u but it work for me 

first fo all this is how i call my api

export const createStockSellPost = async (router, data) => {
    try {
        const formData = new FormData();

        // Append other fields
        formData.append('owner_name', data.owner_name);
        formData.append('price', data.price);
        formData.append('quantity', data.quantity);
        formData.append('region_id', data.region_id);
        formData.append('sector_id', data.sector_id);

        // Append photos
        if (data.photos && data.photos.length > 0) {
            data.photos.forEach((photo, index) => {
                formData.append(`photos[]`, {
                    uri: photo.uri,
                    type: photo.mimeType,
                    name: photo.fileName,
                });
            });
        }

        // Log FormData contents
        const formDataEntries = logFormData(formData);
        console.log("FormData Entries:", formDataEntries);

        const response = await axiosInstance.post(`/${router}`, formData);
        console.log(response);
        if (response.status === 200) {
            return {
                data: response.data,
            };
        }
    } catch (error) {
        console.log(error);
        throw new Error(error.message || 'Error creating stock sell post');
    }
};


and this is my headers

const axiosInstance = axios.create({
    // baseURL: mode === 'development' ? process.env.EXPO_PUBLIC_DEV_URI : process.env.EXPO_PUBLIC_PROD_URI,
    baseURL: process.env.EXPO_PUBLIC_DEV_URI,
    headers: {
        'Content-Type': 'multipart/form-data',
        'Accept': 'application/json',
    },
});

hope it will work for u as well

**Comment by RahulSingh225** [comment]
> 2024, and I still have this problem, it doesn't happen every time, only sometimes and on Android.
> 
> As I said, it doesn't happen all the time, only once in a while, I haven't found a pattern for it.
> 
> I know that the file is filled, I have a log showing it before and in the request in the flipper the formData appears filled.
> 
> But out of nowhere, sometimes this network error happens, and when it happens, if you try to submit again, it works normally.
> 
> react native: 0.71.1 axios: 1.6.7
> 
> ```js
>      console.log("file", file)
>     const formData = new FormData();
>     formData.append('file', file);
> 
>     return api.put<IBaseResponse<IOnboardingResponse>>(
>       submitEvidenceRoute,
>       formData,
>       {
>         headers: { 'Content-Type': 'multipart/form-data' },
>       },
>     );
> ```
> 
> I tried using mimo and the solutions above, but nothing... the worst thing is that it only happens once in a while, so I always have to test a lot to see if it solves it or not...



> 2024, and I still have this problem, it doesn't happen every time, only sometimes and on Android.
> 
> As I said, it doesn't happen all the time, only once in a while, I haven't found a pattern for it.
> 
> I know that the file is filled, I have a log showing it before and in the request in the flipper the formData appears filled.
> 
> But out of nowhere, sometimes this network error happens, and when it happens, if you try to submit again, it works normally.
> 
> react native: 0.71.1 axios: 1.6.7
> 
> ```js
>      console.log("file", file)
>     const formData = new FormData();
>     formData.append('file', file);
> 
>     return api.put<IBaseResponse<IOnboardingResponse>>(
>       submitEvidenceRoute,
>       formData,
>       {
>         headers: { 'Content-Type': 'multipart/form-data' },
>       },
>     );
> ```
> 
> I tried using mimo and the solutions above, but nothing... the worst thing is that it only happens once in a while, so I always have to test a lot to see if it solves it or not...

This only happens if you send the request first time, the weird thing is axios does not send the request first time, after that if we request second third time it works as expected... there is no detailed stack trace to know as of why axios is hitting network error.

**Comment by rboy0509** [comment]
i just set    type: 'image/png', and it works

**Comment by gold-mouse** [comment]
> I faced exactly the same issue today and managed to address it by replacing the image type with 'image/jpeg'.
> 
> **Old Code:**
> 
> const data = new FormData();
> data.append('image', {
>   name: image.name,
>   type: 'image',
>   uri: image.path,
> });
> 
> const response = await axios.post('/', data, {
>   headers: {'content-type': 'multipart/form-data'},
> });
> **New Code:**
> 
> const data = new FormData();
> data.append('image', {
>   name: image.name,
>   type: 'image/jpeg',
>   uri: image.path,
> });
> 
> const response = await axios.post('/', data, {
>   headers: {'content-type': 'multipart/form-data'},
> });
> This solved the issue for me. Hope it helps!

Thank you very much, I got full stress because of this issue, but now it is fixed by your. :)
Thank you very much again.

**Comment by ermix3** [comment]
## The same issue "Network Error", this only shown in expo-go or emulator android not in the web. also Get request fine but POST or PATCH with form-data not working for me below you found all details. please help 

### This is ***package.json***


![Image](https://github.com/user-attachments/assets/bb16c3ea-10bf-4d21-9bda-57b2c73d904d)

### This is my code in react-native ***PostService.tsx***

![Image](https://github.com/user-attachments/assets/25c68dd1-25c9-4606-9f8b-4ea81d9839aa)


### This is my backend [springboot] method to create new post ***PostController.java***

![Image](https://github.com/user-attachments/assets/a9b0cda1-5e6e-46b3-b18f-c8fd0828ebb3)

> This is the error in console:

![Image](https://github.com/user-attachments/assets/266818ba-8ae4-4179-b371-7df3698d145f)

**Comment by Mohammed-Elmahdaoui** [comment]
same issue here :(

**Comment by ermix3** [comment]
> same issue here :(

I found this solution:

```js
  
formData.append('post',{
      string: JSON.stringify(post),
      type: "application/json",
    });

```
Maybe work for you.

**Comment by zegenerative** [comment]
Still having this issue 
SDK 52
Axios 1.8.3

```JS
// creating formData
 const formData = new FormData();
            if (data.image) {
                formData.append('image', {
                    uri: data.image.uri,
                    name: data.image?.name ?? "image.jpg",
                    type: Platform.OS === "android" || !data.image.type ? "image/jpeg" : data.image.type,
                } as any);
            }
// trying to post, (not setting headers as mentioned everywhere)
axios.post(`${API_URL}`, formData)
```

working in iOS

**Comment by gold-mouse** [comment]
> Still having this issue SDK 52 Axios 1.8.3
> 
> // creating formData
>  const formData = new FormData();
>             if (data.image) {
>                 formData.append('image', {
>                     uri: data.image.uri,
>                     name: data.image?.name ?? "image.jpg",
>                     type: Platform.OS === "android" || !data.image.type ? "image/jpeg" : data.image.type,
>                 } as any);
>             }
> // trying to post, (not setting headers as mentioned everywhere)
> axios.post(`${API_URL}`, formData)
> working in iOS

Do you try to add size property also?
I faced this issue, but I've solved it by appending correct formated data to FormData.
`
{ type: "application/pdf", uri: selectedFile.uri, name: selectedFile.name, size: selectedFile.size }
`

**Comment by sayeed007** [comment]
> > same issue here :(
> 
> I found this solution:
> 
>   
> formData.append('post',{
>       string: JSON.stringify(post),
>       type: "application/json",
>     });
> Maybe work for you.



also I have to add 'Content-Type': 'multipart/form-data', manually inside axios request to make this thing working
const axiosResponse = await axios.post(`${API_URL}`, formData, {
                    headers: {
                        'Authorization': `Bearer ${ACCESS_TOKEN}`,
                        'Content-Type': 'multipart/form-data',
                    },
                });

**Comment by jasonsaayman** [comment]
Closing see #6968
