### ISSUE TITLE
"onUploadProgress" executes again when the request completed or failed

### ISSUE THREAD

**Issue by Cheese-Yu** [axios/axios#6550]
### Describe the bug

1. "onUploadProgress" executes again when the request completed or failed. After print `[upload success]` or `[upload error]`, `[onUploadProgress]` will print agin.
![image](https://github.com/user-attachments/assets/5e7c8c14-24a2-445f-acc6-a4b9aa87f29f)

2. `progressEvent.progress` value is incorrect.   
* If upload failed, `progressEvent.progress` increases dramatically in an instant, some times is `1`.  
![image](https://github.com/user-attachments/assets/c0416a72-1191-4040-a6f1-2241e222845f)
* If upload success, `progressEvent.progress` last value maybe is not `1`.
![image](https://github.com/user-attachments/assets/641f7209-fb51-499b-8cdb-7b1db6250445)

### Code snippet

```js
try {
    const res = await axios.put(url, file, {
      headers,
      onUploadProgress: progressEvent => {
        console.log('[onUploadProgress]: ', progressEvent.progress)
      },
      signal: controller?.signal,
    });
    console.log('[upload success]: ', res)
} catch(e) {
    // statements
    console.error('[upload error]: ', e);
}
```

### Expected behavior

When the request completed or failed, onUploadProgress shouldn't executes.

### Axios Version

1.7.2

### Browser

Chrome

**Comment by DigitalBrainJS** [comment]
> Axios Version
> 1.7.2

I believe this was fixed in `1.7.3`, have you tried it?

**Comment by Cheese-Yu** [comment]
> > Axios Version
> > 1.7.2
> 
> I believe this was fixed in `1.7.3`, have you tried it?  

I tried `1.7.4`, problem about `"onUploadProgress" executes again when the request completed or failed` was fixed.
But `"progressEvent.progress" value increases dramatically in an instant when request fail` still exist.

![image](https://github.com/user-attachments/assets/6000d2cc-80c7-43f0-a37e-909afd780c1f)

**Comment by DigitalBrainJS** [comment]
Can you share the full log of the event? Is that the default `xhr` adapter or `fetch`? 
Is there additional information about the cause of the network error?

```js
      onUploadProgress(e) {
        console.log('upload', JSON.stringify(e));
      },
```

**Comment by xzhdev** [comment]
I'm having the same problem, is it Contenet-Length or transfer-encoding that is returned in your response header? @Cheese-Yu

**Comment by Cheese-Yu** [comment]
* Use Chrome DevTools network throttling "offline"
![image](https://github.com/user-attachments/assets/4f843226-4477-4f0c-a1ff-cb0b9e6638fd)
* Close my computer "WIFI"
![image](https://github.com/user-attachments/assets/574fde54-aa7f-411b-9ef4-e2630549c642)

Maybe problem `"progressEvent.progress" value increases dramatically in an instant when request fail` isn't caused by axios. Thanks.

**Comment by Cheese-Yu** [comment]
> I'm having the same problem, is it Contenet-Length or transfer-encoding that is returned in your response header? @Cheese-Yu

No.

**Comment by jasonsaayman** [comment]
Thanks for the report and follow-up. The extra `onUploadProgress` call after completion was fixed in axios 1.7.3. The remaining progress jump during forced offline/network failure appears to come from the browser's progress event behaviour rather than axios itself.

I am closing this as fixed/answered. If a current axios release still emits an extra completion event, please open a new minimal repro with the adapter used and the full serialised progress event log.
